#!/bin/bash

echo "🔧 Configuração do GitHub OAuth"
echo "================================"
echo ""
echo "Para configurar as credenciais do GitHub:"
echo ""
echo "1. Acesse sua OAuth App no GitHub:"
echo "   https://github.com/settings/applications/3187555"
echo ""
echo "2. Copie o Client ID e Client Secret"
echo ""
echo "3. Execute um dos comandos abaixo:"
echo ""
echo "   Opção 1 - Variáveis de ambiente:"
echo "   export GITHUB_CLIENT_ID='seu-client-id'"
echo "   export GITHUB_CLIENT_SECRET='seu-client-secret'"
echo "   npm run start:dev"
echo ""
echo "   Opção 2 - Arquivo .env (recomendado):"
echo "   Crie um arquivo .env na raiz do projeto com:"
echo "   GITHUB_CLIENT_ID=seu-client-id"
echo "   GITHUB_CLIENT_SECRET=seu-client-secret"
echo ""
echo "4. Reinicie o backend:"
echo "   npm run start:dev"
echo ""
echo "✅ Sua OAuth App está configurada com:"
echo "   - Homepage URL: http://localhost:5000"
echo "   - Callback URL: http://localhost:5000/settings"
echo ""

