name: Deploy da Aplicação

# Controla quando a ação será executada
on:
  # Dispara o workflow em eventos de push para a branch main
  push:
    branches: [ "main" ]
  # Permite executar este workflow manualmente através da interface do GitHub
  workflow_dispatch:

jobs:
  # Job de deploy
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Faz o deploy via SSH usando senha
      - name: Deploy para o servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 191.252.177.174
          username: root
          password: "MZE36vkT@#"
          script: |
            cd /var/www/timeboard/votacao-backend
            git pull origin main
            # Install Node.js dependencies
            yarn install --frozen-lockfile
            # Check if pm2 is installed globally, if not install it
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            # Restart or start the application
            pm2 describe votacao-backend > /dev/null
            if [ $? -eq 0 ]; then
              pm2 restart votacao-backend
            else
              pm2 start yarn --name "votacao-backend" -- start
            fi
            # Save PM2 process list
            pm2 save 